### ISSUE TITLE
start fail with empty config.yml

### ISSUE THREAD

**Issue by andreasschulze** [mail-de/mailheadercheck#5]
if config.yml do not include `debug = 0` or `debug = 1, the milter do not start:

```
Traceback (most recent call last):
  File "/mailheadercheck", line 42, in <module>
    logging = Logger.getStdoutLogger(config)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/lib/utility.py", line 154, in getStdoutLogger
    level = logging.DEBUG if config['debug'] == 1 else logging.INFO
                             ~~~~~~^^^^^^^^^
KeyError: 'debug'
```

-> there should be a default in the code

**Comment by andreasschulze** [comment]
also, `log_privacy_mode = 0` or `log_privacy_mode = 1`must be present in config.yml, otherwise:

```
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/Milter/__init__.py", line 855, in <lambda>
    milter.set_eom_callback(lambda ctx: ctx.getpriv().eom())
                                        ^^^^^^^^^^^^^^^^^^^
  File "/lib/mailheadercheckmilter.py", line 194, in eom
    elif self.__config['log_privacy_mode'] == 1:
         ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^
KeyError: 'log_privacy_mode'
```

same: there should be a default in the code

**Comment by andreasschulze** [comment]
that issue got fixed in brach v2024.1, thanks

**Comment by PHPGangsta** [comment]
Closed by v2024.1 (which is now in "main" branch)
